# Task 3 will be focusing on training on "n" number of lanes and testing on "n+1" number of lanes. For now, all
# training and testing sets are going to have the same number of traffic densities

levels:
  grade1:
    train:
      total: 1000
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.20],[70kmh,no-traffic,0.20],[100kmh,no-traffic,0.20], #60%
                   [50kmh,low-density,0.07],[70kmh,low-density,0.07],[100kmh,low-density,0.06], #20%,
                   [50kmh,mid-density,0.05],[70kmh,mid-density,0.05],[100kmh,mid-density,0.05], #15%
                   [50kmh,high-density,0.02],[70kmh,high-density,0.02],[100kmh,high-density,0.01]] #5%
           stops: null
        2lane_curvy_t:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.20],[70kmh,no-traffic,0.20],[100kmh,no-traffic,0.20], #60%
                   [50kmh,low-density,0.07],[70kmh,low-density,0.07],[100kmh,low-density,0.06], #20%,
                   [50kmh,mid-density,0.05],[70kmh,mid-density,0.05],[100kmh,mid-density,0.05], #15%
                   [50kmh,high-density,0.02],[70kmh,high-density,0.02],[100kmh,high-density,0.01]] #5%
           stops: null
    test:
      total: 300
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 1
           specs: [[50kmh,no-traffic,0.15],[70kmh,no-traffic,0.15],[100kmh,no-traffic,0.15], #45%
                   [50kmh,low-density,0.085],[70kmh,low-density,0.085],[100kmh,low-density,0.08], #25%,
                   [50kmh,mid-density,0.07],[70kmh,mid-density,0.07],[100kmh,mid-density,0.06], #20%
                   [50kmh,high-density,0.035],[70kmh,high-density,0.035],[100kmh,high-density,0.03]] #10%
           stops: null
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
  grade2:
    train:
      total: 500
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.3
           specs: [[50kmh,no-traffic,0.05],[70kmh,no-traffic,0.05],[100kmh,no-traffic,0.05], #15%
                   [50kmh,low-density,0.20],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #60%,
                   [50kmh,mid-density,0.07],[70kmh,mid-density,0.07],[100kmh,mid-density,0.06], #20%
                   [50kmh,high-density,0.02],[70kmh,high-density,0.02],[100kmh,high-density,0.01]] #5%
           stops: null
        2lane_curvy_t:
           percent: 0.3
           specs: [[50kmh,no-traffic,0.05],[70kmh,no-traffic,0.05],[100kmh,no-traffic,0.05], #15%
                   [50kmh,low-density,0.20],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #60%,
                   [50kmh,mid-density,0.07],[70kmh,mid-density,0.07],[100kmh,mid-density,0.06], #20%
                   [50kmh,high-density,0.02],[70kmh,high-density,0.02],[100kmh,high-density,0.01]] #5%
           stops: null
        3lane_t:
           percent: 0.4
           specs: [[50kmh,no-traffic,0.05],[70kmh,no-traffic,0.05],[100kmh,no-traffic,0.05], #15%
                   [50kmh,low-density,0.20],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #60%,
                   [50kmh,mid-density,0.07],[70kmh,mid-density,0.07],[100kmh,mid-density,0.06], #20%
                   [50kmh,high-density,0.02],[70kmh,high-density,0.02],[100kmh,high-density,0.01]] #5%
           stops: null
    test:
      total: 300
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 0.8
           specs: [[50kmh,no-traffic,0.07],[70kmh,no-traffic,0.07],[100kmh,no-traffic,0.06], #20%
                   [50kmh,low-density,0.15],[70kmh,low-density,0.15],[100kmh,low-density,0.15], #45%,
                   [50kmh,mid-density,0.085],[70kmh,mid-density,0.085],[100kmh,mid-density,0.08], #25%
                   [50kmh,high-density,0.035],[70kmh,high-density,0.035],[100kmh,high-density,0.03]] #10%
           stops: null
        3lane_c:
           percent: 0.2
           specs: [[50kmh,no-traffic,0.07],[70kmh,no-traffic,0.07],[100kmh,no-traffic,0.06], #20%
                   [50kmh,low-density,0.15],[70kmh,low-density,0.15],[100kmh,low-density,0.15], #45%,
                   [50kmh,mid-density,0.085],[70kmh,mid-density,0.085],[100kmh,mid-density,0.08], #25%
                   [50kmh,high-density,0.035],[70kmh,high-density,0.035],[100kmh,high-density,0.03]] #10%
           stops: null
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
  grade3:
    train:
      total: 500
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.2
           specs: [[50kmh,no-traffic,0.02],[70kmh,no-traffic,0.02],[100kmh,no-traffic,0.01], #5%
                   [50kmh,low-density,0.05],[70kmh,low-density,0.05],[100kmh,low-density,0.05], #15%,
                   [50kmh,mid-density,0.20],[70kmh,mid-density,0.20],[100kmh,mid-density,0.20], #60%
                   [50kmh,high-density,0.07],[70kmh,high-density,0.07],[100kmh,high-density,0.06]] #20%
           stops: null
        2lane_curvy_t:
           percent: 0.4
           specs: [[50kmh,no-traffic,0.02],[70kmh,no-traffic,0.02],[100kmh,no-traffic,0.01], #5%
                   [50kmh,low-density,0.05],[70kmh,low-density,0.05],[100kmh,low-density,0.05], #15%,
                   [50kmh,mid-density,0.20],[70kmh,mid-density,0.20],[100kmh,mid-density,0.20], #60%
                   [50kmh,high-density,0.07],[70kmh,high-density,0.07],[100kmh,high-density,0.06]] #20%
           stops: null
        3lane_t:
           percent: 0.4
           specs: [[50kmh,no-traffic,0.02],[70kmh,no-traffic,0.02],[100kmh,no-traffic,0.01], #5%
                   [50kmh,low-density,0.05],[70kmh,low-density,0.05],[100kmh,low-density,0.05], #15%,
                   [50kmh,mid-density,0.20],[70kmh,mid-density,0.20],[100kmh,mid-density,0.20], #60%
                   [50kmh,high-density,0.07],[70kmh,high-density,0.07],[100kmh,high-density,0.06]] #20%
           stops: null
    test:
      total: 300
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.035],[70kmh,no-traffic,0.035],[100kmh,no-traffic,0.03], #10%
                   [50kmh,low-density,0.07],[70kmh,low-density,0.07],[100kmh,low-density,0.06], #20%,
                   [50kmh,mid-density,0.15],[70kmh,mid-density,0.15],[100kmh,mid-density,0.15], #45%
                   [50kmh,high-density,0.08],[70kmh,high-density,0.08],[100kmh,high-density,0.09]] #25%
           stops: null
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
  grade4:
    train:
      total: 500
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.2
           specs: [[50kmh,no-traffic,0.02],[70kmh,no-traffic,0.02],[100kmh,no-traffic,0.01], #5%
                   [50kmh,low-density,0.05],[70kmh,low-density,0.05],[100kmh,low-density,0.05], #15%,
                   [50kmh,mid-density,0.07],[70kmh,mid-density,0.07],[100kmh,mid-density,0.06], #20%
                   [50kmh,high-density,0.20],[70kmh,high-density,0.20],[100kmh,high-density,0.20]] #60%
           stops: null
        3lane_t:
           percent: 0.4
           specs: [[50kmh,no-traffic,0.02],[70kmh,no-traffic,0.02],[100kmh,no-traffic,0.01], #5%
                   [50kmh,low-density,0.05],[70kmh,low-density,0.05],[100kmh,low-density,0.05], #15%,
                   [50kmh,mid-density,0.07],[70kmh,mid-density,0.07],[100kmh,mid-density,0.06], #20%
                   [50kmh,high-density,0.20],[70kmh,high-density,0.20],[100kmh,high-density,0.20]] #60%
           stops: null
        2lane_curvy_t:
           percent: 0.4
           specs: [[50kmh,no-traffic,0.02],[70kmh,no-traffic,0.02],[100kmh,no-traffic,0.01], #5%
                   [50kmh,low-density,0.05],[70kmh,low-density,0.05],[100kmh,low-density,0.05], #15%,
                   [50kmh,mid-density,0.07],[70kmh,mid-density,0.07],[100kmh,mid-density,0.06], #20%
                   [50kmh,high-density,0.20],[70kmh,high-density,0.20],[100kmh,high-density,0.20]] #60%
           stops: null
    test:
      total: 300
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        3lane_c:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.035],[70kmh,no-traffic,0.035],[100kmh,no-traffic,0.03], #10%
                   [50kmh,low-density,0.07],[70kmh,low-density,0.07],[100kmh,low-density,0.06], #20%,
                   [50kmh,mid-density,0.08],[70kmh,mid-density,0.08],[100kmh,mid-density,0.09], #25%
                   [50kmh,high-density,0.15],[70kmh,high-density,0.15],[100kmh,high-density,0.15]] #45%
           stops: null
        4lane_c:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.035],[70kmh,no-traffic,0.035],[100kmh,no-traffic,0.03], #10%
                   [50kmh,low-density,0.07],[70kmh,low-density,0.07],[100kmh,low-density,0.06], #20%,
                   [50kmh,mid-density,0.08],[70kmh,mid-density,0.08],[100kmh,mid-density,0.09], #25%
                   [50kmh,high-density,0.15],[70kmh,high-density,0.15],[100kmh,high-density,0.15]] #45%
           stops: null
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
  no-traffic:
    train:
      total: 100
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.4
           specs: [[50kmh,no-traffic,0.33],[70kmh,no-traffic,0.34],[100kmh,no-traffic,0.33]]
           stops: null
        3lane_t:
           percent: 0.4
           specs: [[50kmh,no-traffic,0.33],[70kmh,no-traffic,0.34],[100kmh,no-traffic,0.33]]
           stops: null
        2lane_curvy_t:
           percent: 0.2
           specs: [[50kmh,no-traffic,0.33],[70kmh,no-traffic,0.34],[100kmh,no-traffic,0.33]]
           stops: null
    test:
      total: 100
      ego_missions:
      - start: north-NS
        end:   east-WE
      intersection_types:
        2lane_c:
           percent: 1
           specs: [[50kmh,no-traffic,0.33],[70kmh,no-traffic,0.34],[100kmh,no-traffic,0.33]]
           stops: null
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
  low-density:
    train:
      total: null
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[50kmh,low-density,0.33],[70kmh,low-density,0.34],[100kmh,low-density,0.33]]
           stops: null
    test:
      total: null
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 1
           specs: [[50kmh,low-density,0.33],[70kmh,low-density,0.34],[100kmh,low-density,0.33]]
           stops: null
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
  mid-density:
    train:
      total: null
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[50kmh,mid-density,0.33],[70kmh,mid-density,0.34],[100kmh,mid-density,0.33]]
           stops: null
    test:
      total: null
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 1
           specs: [[50kmh,mid-density,0.33],[70kmh,mid-density,0.34],[100kmh,mid-density,0.33]]
           stops: null
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
  high-density:
    train:
      total: 1
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[50kmh,high-density,0.33],[70kmh,high-density,0.34],[100kmh,high-density,0.33]]
           stops: null
    test:
      total: 250
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 0.5
           specs: [[50kmh,high-density,0.33],[70kmh,high-density,0.34],[100kmh,high-density,0.33]]
           stops: null
        3lane_c:
           percent: 0.5
           specs: [[50kmh,high-density,0.33],[70kmh,high-density,0.34],[100kmh,high-density,0.33]]
           stops: null
    
  constant-flow:
    train:
      total: 1000
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.4
           specs: [[50kmh,constant-flow,0.33],[70kmh,constant-flow,0.34],[100kmh,constant-flow,0.33]] #100%
           stops: null
        3lane_t:
           percent: 0.4
           specs: [[50kmh,constant-flow,0.33],[70kmh,constant-flow,0.34],[100kmh,constant-flow,0.33]] #100%
           stops: null
        2lane_curvy_t:
           percent: 0.2
           specs: [[50kmh,constant-flow,0.33],[70kmh,constant-flow,0.34],[100kmh,constant-flow,0.33]] #100%
           stops: null
    test:
      total: 100
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 1
           specs: [[50kmh,constant-flow,0.33],[70kmh,constant-flow,0.34],[100kmh,constant-flow,0.33]] #100%
           stops: null

  # Evaluation only scenarios ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  eval-equal:
    train:
      total: 1
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[50kmh,high-density,0.33],[70kmh,high-density,0.34],[100kmh,high-density,0.33]]
           stops: null
    test:
      total: 1200
      ego_missions:
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.08],[70kmh,no-traffic,0.09],[100kmh,no-traffic,0.08], #25%
                   [50kmh,low-density,0.08],[70kmh,low-density,0.09],[100kmh,low-density,0.08], #25%
                   [50kmh,mid-density,0.08],[70kmh,mid-density,0.09],[100kmh,mid-density,0.08], #25%
                   [50kmh,high-density,0.08],[70kmh,high-density,0.09],[100kmh,high-density,0.08]] #25%
           stops: null
        3lane_c:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.08],[70kmh,no-traffic,0.09],[100kmh,no-traffic,0.08], #25%
                   [50kmh,low-density,0.08],[70kmh,low-density,0.09],[100kmh,low-density,0.08], #25%
                   [50kmh,mid-density,0.08],[70kmh,mid-density,0.09],[100kmh,mid-density,0.08], #25%
                   [50kmh,high-density,0.08],[70kmh,high-density,0.09],[100kmh,high-density,0.08]] #25%
           stops: null