# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import smarts.proto.action_pb2 as action__pb2
import smarts.proto.observation_pb2 as observation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="worker.proto",
    package="worker",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0cworker.proto\x12\x06worker\x1a\x0c\x61\x63tion.proto\x1a\x11observation.proto" \n\rSpecification\x12\x0f\n\x07payload\x18\x01 \x01(\x0c"\x08\n\x06Status2o\n\x06Worker\x12\x30\n\x05\x62uild\x12\x15.worker.Specification\x1a\x0e.worker.Status"\x00\x12\x33\n\x03\x61\x63t\x12\x19.observation.Observations\x1a\x0f.action.Actions"\x00\x62\x06proto3',
    dependencies=[
        action__pb2.DESCRIPTOR,
        observation__pb2.DESCRIPTOR,
    ],
)


_SPECIFICATION = _descriptor.Descriptor(
    name="Specification",
    full_name="worker.Specification",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="payload",
            full_name="worker.Specification.payload",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=57,
    serialized_end=89,
)


_STATUS = _descriptor.Descriptor(
    name="Status",
    full_name="worker.Status",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=91,
    serialized_end=99,
)

DESCRIPTOR.message_types_by_name["Specification"] = _SPECIFICATION
DESCRIPTOR.message_types_by_name["Status"] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Specification = _reflection.GeneratedProtocolMessageType(
    "Specification",
    (_message.Message,),
    {
        "DESCRIPTOR": _SPECIFICATION,
        "__module__": "worker_pb2"
        # @@protoc_insertion_point(class_scope:worker.Specification)
    },
)
_sym_db.RegisterMessage(Specification)

Status = _reflection.GeneratedProtocolMessageType(
    "Status",
    (_message.Message,),
    {
        "DESCRIPTOR": _STATUS,
        "__module__": "worker_pb2"
        # @@protoc_insertion_point(class_scope:worker.Status)
    },
)
_sym_db.RegisterMessage(Status)


_WORKER = _descriptor.ServiceDescriptor(
    name="Worker",
    full_name="worker.Worker",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=101,
    serialized_end=212,
    methods=[
        _descriptor.MethodDescriptor(
            name="build",
            full_name="worker.Worker.build",
            index=0,
            containing_service=None,
            input_type=_SPECIFICATION,
            output_type=_STATUS,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="act",
            full_name="worker.Worker.act",
            index=1,
            containing_service=None,
            input_type=observation__pb2._OBSERVATIONS,
            output_type=action__pb2._ACTIONS,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name["Worker"] = _WORKER

# @@protoc_insertion_point(module_scope)
