name: ppo-cruising

agent:
  state:
    wrapper:
      name: Simple
    features:
      distance_to_center: True
      speed: True
      steering: True
      heading_errors: [10, skip]
      lane_its_info: true
      proximity: true
  action:
    type: 0  # 0 for continuous, 1 for discrete
  adapter_type: cruising

interface:
  max_episode_steps: 1000
  neighborhood_vehicles:
    radius: 50
  waypoints:
    lookahead: 50  # larger than size of heading errors
  ogm:
    width: 64
    height: 64
    resolution: 0.25


policy:
  framework: rllib
  trainer:
    path: ray.rllib.agents.ppo
    name: PPOTrainer

run:
  checkpoint_freq: 40
  checkpoint_at_end: True
  max_failures: 1000
  resume: False
  export_formats: [model, checkpoint]
  stop:
    time_total_s: 14400
  config:
    log_level: WARN
    num_workers: 1
    num_gpus: 0
    horizon: 1000
    lambda: 0.95
    lr: 1e-4
    clip_param: 0.2
    num_sgd_iter: 10
    sgd_minibatch_size: 1024
    train_batch_size: 30720
