levels:
  hijack:
    train:
      total: 10
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[70kmh,p-test,1]]
           stops: null
    test:
      total: 10
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[70kmh,p-test,1]]
           stops: null
  no-traffic:
    train:
      total: 10000
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.34],[70kmh,no-traffic,0.33],[100kmh,no-traffic,0.33]]
           stops: null
        3lane_t:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.34],[70kmh,no-traffic,0.33],[100kmh,no-traffic,0.33]]
           stops: null
    test:
      total: 200
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.34],[70kmh,no-traffic,0.33],[100kmh,no-traffic,0.33]]
           stops: null
        3lane_c:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.34],[70kmh,no-traffic,0.33],[100kmh,no-traffic,0.33]]
           stops: null
  easy:
    train:
      total: 10000
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.2
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], #33%,
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01], #3%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
           stops: null
        2lane_curvy_t:
           percent: 0.4
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], #33%
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01], #3%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
           stops: null
        3lane_t:
           percent: 0.4
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], #33%
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01], #3%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
           stops: null
    test:
      total: 200
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 0.5
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], #33%
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01], #3%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
           stops: null
        3lane_c:
           percent: 0.5
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], #33%
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01], #3%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
           stops: null
  hard:
    train:
      total: 10000
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.2
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.2],[100kmh,high-density,0.2], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], #33%
                   [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01], # 3%
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01]] #3%
           stops: null

        2lane_curvy_t:
           percent: 0.4
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.2],[100kmh,high-density,0.2], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11],
                   [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01], # 3%
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01]] #3%
           stops: null
        3lane_t:
           percent: 0.4
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.2],[100kmh,high-density,0.2], # 61%
                  [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], # 33%
                  [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01], # 3%
                  [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01]] #3%
           stops: null
    test:
      total: 200
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 0.5
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.2],[100kmh,high-density,0.2], #61%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01]] # 3%]
           stops: null
        3lane_c:
           percent: 0.5
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.2],[100kmh,high-density,0.2], #61%,
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01]] # 3%
           stops: null
  # ----------------------------------------- SIMPLE LEVELS ------------------------------------------
  simple-v0:
    train:
      total: 30
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
        start_offset: [110, 120]
        end_offset:   [10, 10]
      intersection_types:
        2lane_t:
           percent: 0.2
           specs: [[50kmh,simple-v0,0.33],[70kmh,simple-v0,0.34],[100kmh,simple-v0,0.33]]
           stops: null
        3lane_t:
           percent: 0.1
           specs: [[50kmh,simple-v0,0.33],[70kmh,simple-v0,0.34],[100kmh,simple-v0,0.33]]
           stops: null
        4lane_t:
           percent: 0.2
           specs: [[50kmh,simple-v0,0.33],[70kmh,simple-v0,0.34],[100kmh,simple-v0,0.33]]
           stops: null
        2lane_c:
           percent: 0.2
           specs: [[50kmh,simple-v0,0.33],[70kmh,simple-v0,0.34],[100kmh,simple-v0,0.33]]
           stops: null
        3lane_c:
           percent: 0.1
           specs: [[50kmh,simple-v0,0.33],[70kmh,simple-v0,0.34],[100kmh,simple-v0,0.33]]
           stops: null
        4lane_c:
           percent: 0.2
           specs: [[50kmh,simple-v0,0.33],[70kmh,simple-v0,0.34],[100kmh,simple-v0,0.33]]
           stops: null
    test:
      total: 1
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
        start_offset: [100, 115]
        end_offset:   [90, 100]
      intersection_types:
        2lane_c:
           percent: 0.1
           specs: [[50kmh,simple-v0,0.33],[70kmh,simple-v0,0.34],[100kmh,simple-v0,0.33]]
           stops: null
           
  simple-v1:
    train:
      total: 30
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
        start_offset: [90, 120]
        end_offset:   [90, 100]
      intersection_types:
        2lane_t:
           percent: 0.2
           specs: [[50kmh,simple-v1,0.33],[70kmh,simple-v1,0.34],[100kmh,simple-v1,0.33]]
           stops: null
        3lane_t:
           percent: 0.1
           specs: [[50kmh,simple-v1,0.33],[70kmh,simple-v1,0.34],[100kmh,simple-v1,0.33]]
           stops: null
        4lane_t:
           percent: 0.2
           specs: [[50kmh,simple-v1,0.33],[70kmh,simple-v1,0.34],[100kmh,simple-v1,0.33]]
           stops: null
        2lane_c:
           percent: 0.2
           specs: [[50kmh,simple-v1,0.33],[70kmh,simple-v1,0.34],[100kmh,simple-v1,0.33]]
           stops: null
        3lane_c:
           percent: 0.1
           specs: [[50kmh,simple-v1,0.33],[70kmh,simple-v1,0.34],[100kmh,simple-v1,0.33]]
           stops: null
        4lane_c:
           percent: 0.2
           specs: [[50kmh,simple-v1,0.33],[70kmh,simple-v1,0.34],[100kmh,simple-v1,0.33]]
           stops: null
    test:
      total: 1
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
        start_offset: [100, 115]
        end_offset:   [90, 100]
      intersection_types:
        2lane_c:
           percent: 0.1
           specs: [[50kmh,simple-v1,0.33],[70kmh,simple-v1,0.34],[100kmh,simple-v1,0.33]]
           stops: null
  simple-v2:
    train:
      total: 30
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
        start_offset: [120, 120]
        end_offset:   [80, 80]
      intersection_types:
        2lane_t:
           percent: 0.2
           specs: [[50kmh,simple-v2,0.33],[70kmh,simple-v2,0.34],[100kmh,simple-v2,0.33]]
           stops: null
        3lane_t:
           percent: 0.1
           specs: [[50kmh,simple-v2,0.33],[70kmh,simple-v2,0.34],[100kmh,simple-v2,0.33]]
           stops: null
        4lane_t:
           percent: 0.2
           specs: [[50kmh,simple-v2,0.33],[70kmh,simple-v2,0.34],[100kmh,simple-v2,0.33]]
           stops: null
        2lane_c:
           percent: 0.2
           specs: [[50kmh,simple-v2,0.33],[70kmh,simple-v2,0.34],[100kmh,simple-v2,0.33]]
           stops: null
        3lane_c:
           percent: 0.1
           specs: [[50kmh,simple-v2,0.33],[70kmh,simple-v2,0.34],[100kmh,simple-v2,0.33]]
           stops: null
        4lane_c:
           percent: 0.2
           specs: [[50kmh,simple-v2,0.33],[70kmh,simple-v2,0.34],[100kmh,simple-v2,0.33]]
           stops: null
    test:
      total: 10
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
        start_offset: [100, 115]
        end_offset:   [90, 100]
      intersection_types:
        2lane_c:
           percent: 0.1
           specs: [[50kmh,simple-v2,0.33],[70kmh,simple-v2,0.34],[100kmh,simple-v2,0.33]]
           stops: null
