levels:
  hijack:
    train:
      total: 10
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[70kmh,p-test,1]]
           stops: null
           bubbles: null
    test:
      total: 10
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 1
           specs: [[70kmh,p-test,1]]
           stops: null
           bubbles: null
  no-traffic:
    train:
      total: 10000
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.34],[70kmh,no-traffic,0.33],[100kmh,no-traffic,0.33]]
           stops: null
           bubbles: null
        3lane_t:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.34],[70kmh,no-traffic,0.33],[100kmh,no-traffic,0.33]]
           stops: null
           bubbles: null
    test:
      total: 200
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.34],[70kmh,no-traffic,0.33],[100kmh,no-traffic,0.33]]
           stops: null
           bubbles: null
        3lane_c:
           percent: 0.5
           specs: [[50kmh,no-traffic,0.34],[70kmh,no-traffic,0.33],[100kmh,no-traffic,0.33]]
           stops: null
           bubbles: null
  simple:
    train:
      total: 10000
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
          percent: 0.2
          specs: [[50kmh,no-traffic,0.20],[70kmh,no-traffic,0.20],[100kmh,no-traffic,0.20], #60%
                  [50kmh,low-density,0.14],[70kmh,low-density,0.13],[100kmh,low-density,0.13]] #40%
          stops: null
          bubbles: null
        3lane_t:
          percent: 0.4
          specs: [[50kmh,no-traffic,0.20],[70kmh,no-traffic,0.20],[100kmh,no-traffic,0.20], #60%
                  [50kmh,low-density,0.14],[70kmh,low-density,0.13],[100kmh,low-density,0.13]] #40%
          stops: null
          bubbles: null
        4lane_t:
          percent: 0.4
          specs: [[50kmh,no-traffic,0.20],[70kmh,no-traffic,0.20],[100kmh,no-traffic,0.20], #60%
                  [50kmh,low-density,0.14],[70kmh,low-density,0.13],[100kmh,low-density,0.13]] #40%
          stops: null
          bubbles: null
    test:
      total: 200
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
          percent: 0.5
          specs: [[50kmh,no-traffic,0.20],[70kmh,no-traffic,0.20],[100kmh,no-traffic,0.20], #60%
                  [50kmh,low-density,0.14],[70kmh,low-density,0.13],[100kmh,low-density,0.13]] #40%
          stops: null
          bubbles: null
        3lane_c:
          percent: 0.5
          specs: [[50kmh,no-traffic,0.20],[70kmh,no-traffic,0.20],[100kmh,no-traffic,0.20], #60%
                  [50kmh,low-density,0.14],[70kmh,low-density,0.13],[100kmh,low-density,0.13]] #40%
          stops: null
          bubbles: null

  easy:
    train:
      total: 10000
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.5
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], #33%,
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01], #3%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
           stops: null
           bubbles: null
        3lane_t:
           percent: 0.5
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], #33%
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01], #3%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
           stops: null
           bubbles: null
    test:
      total: 200
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 0.5
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], #33%
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01], #3%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
           stops: null
           bubbles: null
        3lane_c:
           percent: 0.5
           specs: [[50kmh,low-density,0.21],[70kmh,low-density,0.20],[100kmh,low-density,0.20], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], #33%
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01], #3%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] # 3%
           stops: null
           bubbles: null
  medium:
    train:
      total: 10000
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.5
           specs: [[50kmh,mid-density,0.21],[70kmh,mid-density,0.20],[100kmh,mid-density,0.20], #61%
                   [50kmh,low-density,0.11],[70kmh,low-density,0.11],[100kmh,low-density,0.11], #33%,
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01], #3%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] #3%
           stops: null
           bubbles: null
        3lane_t:
           percent: 0.5
           specs: [[50kmh,mid-density,0.21],[70kmh,mid-density,0.20],[100kmh,mid-density,0.20], #61%
                   [50kmh,low-density,0.11],[70kmh,low-density,0.11],[100kmh,low-density,0.11], #33%,
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01], #3%
                   [50kmh,high-density,0.01],[70kmh,high-density,0.01],[100kmh,high-density,0.01]] #3%
           stops: null
           bubbles: null
    test:
      total: 200
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 0.5
           specs: [[50kmh,mid-density,0.21],[70kmh,mid-density,0.20],[100kmh,mid-density,0.20], #61%
                   [50kmh,low-density,0.11],[70kmh,low-density,0.11],[100kmh,low-density,0.11], #33%,
                   [50kmh,high-density,0.02],[70kmh,high-density,0.02],[100kmh,high-density,0.02]] #6%
           stops: null
           bubbles: null
        3lane_c:
           percent: 0.5
           specs: [[50kmh,mid-density,0.21],[70kmh,mid-density,0.20],[100kmh,mid-density,0.20], #61%
                   [50kmh,low-density,0.11],[70kmh,low-density,0.11],[100kmh,low-density,0.11], #33%,
                   [50kmh,high-density,0.02],[70kmh,high-density,0.02],[100kmh,high-density,0.02]] #6%
           stops: null
           bubbles: null
  hard:
    train:
      total: 10000
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
           percent: 0.5
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.2],[100kmh,high-density,0.2], #61%
                   [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], #33%
                   [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01], # 3%
                   [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01]] #3%
           stops: null
           bubbles: null
        3lane_t:
           percent: 0.5
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.2],[100kmh,high-density,0.2], # 61%
                  [50kmh,mid-density,0.11],[70kmh,mid-density,0.11],[100kmh,mid-density,0.11], # 33%
                  [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01], # 3%
                  [50kmh,no-traffic,0.01],[70kmh,no-traffic,0.01],[100kmh,no-traffic,0.01]] #3%
           stops: null
           bubbles: null
    test:
      total: 200
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_c:
           percent: 0.5
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.2],[100kmh,high-density,0.2], #61%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01]] # 3%]
           stops: null
           bubbles: null
        3lane_c:
           percent: 0.5
           specs: [[50kmh,high-density,0.21],[70kmh,high-density,0.2],[100kmh,high-density,0.2], #61%,
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12], #36%
                   [50kmh,low-density,0.01],[70kmh,low-density,0.01],[100kmh,low-density,0.01]] # 3%
           stops: null
           bubbles: null