# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
        - waymo
        # - gym
        # - camera_obs
        # - diagnostics
        # - remote_agent
        # - extras
        # - waymo

# # Optionally declare the Python requirements required to build your docs
# python:
#    install:
#    - requirements: ./requirements.txt

# version: 2

# build:
#   os: ubuntu-22.04
#   tools:
#     python: "3.8"
#   commands:
#     - pip install pelican
#     - pelican --settings docs/pelicanconf.py --output _readthedocs/html/ docs/

sphinx:
  builder: html
  # fail_on_warning: true