# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
  # fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - python -m sphinx -b linkcheck -D linkcheck_timeout=1 docs/ _build/linkcheck
  # commands:
  #   - python -m sphinx -b linkcheck -D linkcheck_timeout=1 docs/ _build/linkcheck
  #   - pip install -e .[camera_obs,doc,train]

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - camera_obs
        - doc
        - train