agent:
  interface:
    action_space: "RelativeTargetPose" # we can only allow `RelativeTargetPose` and `TargetPose`
    img_meters: 50 # Observation image area size in meters.
    img_pixels: 112 # Observation image size in pixels.
  params:
    speed: 20 # Provided to the agent