# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import agent_pb2 as agent__pb2


class AgentStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpawnWorkers = channel.unary_unary(
                '/agent.Agent/SpawnWorkers',
                request_serializer=agent__pb2.Machine.SerializeToString,
                response_deserializer=agent__pb2.Status.FromString,
                )


class AgentServicer(object):
    """Interface exported by the server.
    """

    def SpawnWorkers(self, request, context):
        """A simple RPC.

        Obtains the feature at a given position.

        A feature with an empty name is returned if there's no feature at the given
        position.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpawnWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnWorkers,
                    request_deserializer=agent__pb2.Machine.FromString,
                    response_serializer=agent__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Agent(object):
    """Interface exported by the server.
    """

    @staticmethod
    def SpawnWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.Agent/SpawnWorkers',
            agent__pb2.Machine.SerializeToString,
            agent__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
