# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='agent',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\x17\n\x07Machine\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x06Status\x12\r\n\x05state\x18\x01 \x01(\x05\x32\x38\n\x05\x41gent\x12/\n\x0cSpawnWorkers\x12\x0e.agent.Machine\x1a\r.agent.Status\"\x00\x62\x06proto3'
)




_MACHINE = _descriptor.Descriptor(
  name='Machine',
  full_name='agent.Machine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='agent.Machine.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=45,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='agent.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='agent.Status.state', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['Machine'] = _MACHINE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Machine = _reflection.GeneratedProtocolMessageType('Machine', (_message.Message,), {
  'DESCRIPTOR' : _MACHINE,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.Machine)
  })
_sym_db.RegisterMessage(Machine)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.Status)
  })
_sym_db.RegisterMessage(Status)



_AGENT = _descriptor.ServiceDescriptor(
  name='Agent',
  full_name='agent.Agent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=72,
  serialized_end=128,
  methods=[
  _descriptor.MethodDescriptor(
    name='SpawnWorkers',
    full_name='agent.Agent.SpawnWorkers',
    index=0,
    containing_service=None,
    input_type=_MACHINE,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENT)

DESCRIPTOR.services_by_name['Agent'] = _AGENT

# @@protoc_insertion_point(module_scope)
