# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="master.proto",
    package="master",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0cmaster.proto\x12\x06master"\x13\n\x04Port\x12\x0b\n\x03num\x18\x01 \x01(\x05"#\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t"\t\n\x07Machine"H\n\nConnection\x12\x1e\n\x06status\x18\x01 \x01(\x0b\x32\x0e.master.Status\x12\x11\n\x04port\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x07\n\x05_port2l\n\x06Master\x12,\n\nStopWorker\x12\x0c.master.Port\x1a\x0e.master.Status"\x00\x12\x34\n\x0bSpawnWorker\x12\x0f.master.Machine\x1a\x12.master.Connection"\x00\x62\x06proto3',
)


_PORT = _descriptor.Descriptor(
    name="Port",
    full_name="master.Port",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="num",
            full_name="master.Port.num",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=24,
    serialized_end=43,
)


_STATUS = _descriptor.Descriptor(
    name="Status",
    full_name="master.Status",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="code",
            full_name="master.Status.code",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="msg",
            full_name="master.Status.msg",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=45,
    serialized_end=80,
)


_MACHINE = _descriptor.Descriptor(
    name="Machine",
    full_name="master.Machine",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=82,
    serialized_end=91,
)


_CONNECTION = _descriptor.Descriptor(
    name="Connection",
    full_name="master.Connection",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="master.Connection.status",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="port",
            full_name="master.Connection.port",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="_port",
            full_name="master.Connection._port",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=93,
    serialized_end=165,
)

_CONNECTION.fields_by_name["status"].message_type = _STATUS
_CONNECTION.oneofs_by_name["_port"].fields.append(_CONNECTION.fields_by_name["port"])
_CONNECTION.fields_by_name["port"].containing_oneof = _CONNECTION.oneofs_by_name[
    "_port"
]
DESCRIPTOR.message_types_by_name["Port"] = _PORT
DESCRIPTOR.message_types_by_name["Status"] = _STATUS
DESCRIPTOR.message_types_by_name["Machine"] = _MACHINE
DESCRIPTOR.message_types_by_name["Connection"] = _CONNECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Port = _reflection.GeneratedProtocolMessageType(
    "Port",
    (_message.Message,),
    {
        "DESCRIPTOR": _PORT,
        "__module__": "master_pb2"
        # @@protoc_insertion_point(class_scope:master.Port)
    },
)
_sym_db.RegisterMessage(Port)

Status = _reflection.GeneratedProtocolMessageType(
    "Status",
    (_message.Message,),
    {
        "DESCRIPTOR": _STATUS,
        "__module__": "master_pb2"
        # @@protoc_insertion_point(class_scope:master.Status)
    },
)
_sym_db.RegisterMessage(Status)

Machine = _reflection.GeneratedProtocolMessageType(
    "Machine",
    (_message.Message,),
    {
        "DESCRIPTOR": _MACHINE,
        "__module__": "master_pb2"
        # @@protoc_insertion_point(class_scope:master.Machine)
    },
)
_sym_db.RegisterMessage(Machine)

Connection = _reflection.GeneratedProtocolMessageType(
    "Connection",
    (_message.Message,),
    {
        "DESCRIPTOR": _CONNECTION,
        "__module__": "master_pb2"
        # @@protoc_insertion_point(class_scope:master.Connection)
    },
)
_sym_db.RegisterMessage(Connection)


_MASTER = _descriptor.ServiceDescriptor(
    name="Master",
    full_name="master.Master",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=167,
    serialized_end=275,
    methods=[
        _descriptor.MethodDescriptor(
            name="StopWorker",
            full_name="master.Master.StopWorker",
            index=0,
            containing_service=None,
            input_type=_PORT,
            output_type=_STATUS,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="SpawnWorker",
            full_name="master.Master.SpawnWorker",
            index=1,
            containing_service=None,
            input_type=_MACHINE,
            output_type=_CONNECTION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_MASTER)

DESCRIPTOR.services_by_name["Master"] = _MASTER

# @@protoc_insertion_point(module_scope)
