# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="worker.proto",
    package="worker",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0cworker.proto\x12\x06worker" \n\rSpecification\x12\x0f\n\x07payload\x18\x01 \x01(\x0c"#\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t"\x1e\n\x0bObservation\x12\x0f\n\x07payload\x18\x01 \x01(\x0c"H\n\x06\x41\x63tion\x12\x1e\n\x06status\x18\x01 \x01(\x0b\x32\x0e.worker.Status\x12\x13\n\x06\x61\x63tion\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\t\n\x07_action2h\n\x06Worker\x12\x30\n\x05\x42uild\x12\x15.worker.Specification\x1a\x0e.worker.Status"\x00\x12,\n\x03\x41\x63t\x12\x13.worker.Observation\x1a\x0e.worker.Action"\x00\x62\x06proto3',
)


_SPECIFICATION = _descriptor.Descriptor(
    name="Specification",
    full_name="worker.Specification",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="payload",
            full_name="worker.Specification.payload",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=24,
    serialized_end=56,
)


_STATUS = _descriptor.Descriptor(
    name="Status",
    full_name="worker.Status",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="code",
            full_name="worker.Status.code",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="msg",
            full_name="worker.Status.msg",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=58,
    serialized_end=93,
)


_OBSERVATION = _descriptor.Descriptor(
    name="Observation",
    full_name="worker.Observation",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="payload",
            full_name="worker.Observation.payload",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=95,
    serialized_end=125,
)


_ACTION = _descriptor.Descriptor(
    name="Action",
    full_name="worker.Action",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="worker.Action.status",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="action",
            full_name="worker.Action.action",
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="_action",
            full_name="worker.Action._action",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=127,
    serialized_end=199,
)

_ACTION.fields_by_name["status"].message_type = _STATUS
_ACTION.oneofs_by_name["_action"].fields.append(_ACTION.fields_by_name["action"])
_ACTION.fields_by_name["action"].containing_oneof = _ACTION.oneofs_by_name["_action"]
DESCRIPTOR.message_types_by_name["Specification"] = _SPECIFICATION
DESCRIPTOR.message_types_by_name["Status"] = _STATUS
DESCRIPTOR.message_types_by_name["Observation"] = _OBSERVATION
DESCRIPTOR.message_types_by_name["Action"] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Specification = _reflection.GeneratedProtocolMessageType(
    "Specification",
    (_message.Message,),
    {
        "DESCRIPTOR": _SPECIFICATION,
        "__module__": "worker_pb2"
        # @@protoc_insertion_point(class_scope:worker.Specification)
    },
)
_sym_db.RegisterMessage(Specification)

Status = _reflection.GeneratedProtocolMessageType(
    "Status",
    (_message.Message,),
    {
        "DESCRIPTOR": _STATUS,
        "__module__": "worker_pb2"
        # @@protoc_insertion_point(class_scope:worker.Status)
    },
)
_sym_db.RegisterMessage(Status)

Observation = _reflection.GeneratedProtocolMessageType(
    "Observation",
    (_message.Message,),
    {
        "DESCRIPTOR": _OBSERVATION,
        "__module__": "worker_pb2"
        # @@protoc_insertion_point(class_scope:worker.Observation)
    },
)
_sym_db.RegisterMessage(Observation)

Action = _reflection.GeneratedProtocolMessageType(
    "Action",
    (_message.Message,),
    {
        "DESCRIPTOR": _ACTION,
        "__module__": "worker_pb2"
        # @@protoc_insertion_point(class_scope:worker.Action)
    },
)
_sym_db.RegisterMessage(Action)


_WORKER = _descriptor.ServiceDescriptor(
    name="Worker",
    full_name="worker.Worker",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=201,
    serialized_end=305,
    methods=[
        _descriptor.MethodDescriptor(
            name="Build",
            full_name="worker.Worker.Build",
            index=0,
            containing_service=None,
            input_type=_SPECIFICATION,
            output_type=_STATUS,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Act",
            full_name="worker.Worker.Act",
            index=1,
            containing_service=None,
            input_type=_OBSERVATION,
            output_type=_ACTION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name["Worker"] = _WORKER

# @@protoc_insertion_point(module_scope)
