name: Feature request
description: Suggest an idea for this project not related to bugs
title: "[Feature request] Feature request title"
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Is your feature request related to a problem? Please describe. 
        Give clear and concise description of what the problem is. Ex. I am always frustrated when (...).
      validations:
        required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
        Describe the solution you'd like.
        Give a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
