defaults:
  - base_experiment # see registration of this in examples/control.py
  - env_config: hiway_env-v1
  # - agents_configs@agents_configs.agent_007: lane_control-v0 # agents_configs/lane_control-v0.yaml as agent_configs.agent_007
  # - agents_configs@agents_configs.agent_smith: chase_via_points-v0 # agents_configs/chase_via_points-v0.yaml as agent_configs.agent_smith
  - _self_

episodes: 4
show_config: true
minimum_steps: 1