# Environment variables (optional)
# n_scenarios & n_vehicles can be specified as max(all scenarios/vehicles) or min(1 scenario/vehicle)
n_steps: 2                # total number of steps
n_steps_per_epoch: 2      # number of steps per epoch
n_scenarios: max         # number of training scenarios
n_vehicles: max             # number of vehicles to examine
gpu: False                # whether GPU is used for training