curriculum:
  static:
    toggle: True
    grades:
      # 1: [[gb,no-traffic]] #[[<task>,<level>]]
      1: [[1,constant-flow]]
      # 3: [[gb,grade3]]
      # 4: [[gb,grade4]]
    conditions:
      eval_per_grade: True
      episode_based:
        toggle: True
        cycle: False
      pass_based:
        toggle: False
        pass_rate: 0.95
        sample_rate: 20
        warmup_episodes: 0
  dynamic:
    toggle: False
    tasks_levels_used: [["gb","no-traffic"], ["gb","low-density"], ["gb","mid-density"], ["gb","high-density"], ["1","constant-flow"]]
    sampling_rate: 10
    
      


