name: SMARTS CI Dependencies Linux

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  venv_dir: .venv

jobs:
  update-requirements-linux:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    container: huaweinoah/smarts:v0.4.18-minimal
    steps:
      - name: Install git
        run: |
          add-apt-repository -y ppa:git-core/ppa && \
            apt-get update && \
            apt-get install -y git
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop 
      - name: Update requirements
        run: |
          cd $GITHUB_WORKSPACE
          python3.7 -m venv ${{env.venv_dir}}
          . ${{env.venv_dir}}/bin/activate
          pip install --upgrade pip wheel
          pip install .[test,train,camera-obs]
          pip freeze | grep -v 'smarts' | grep -v 'pkg-resources==0.0.0' > requirements.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'requirements.txt'
          branch: develop
          default_author: user_info 
          message: 'GitHub Actions: Update requirements.txt'