name: SMARTS CI Master

on:
  push:
    branches:
      - master

env:
  venv_dir: .venv/bin/activate

jobs:
  test_learning:
    runs-on: ubuntu-18.04
    container:
      image: gamenotcore/smarts-base
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package Setup
        run: |
          /usr/bin/Xorg \
            -noreset \
            +extension GLX \
            +extension RANDR \
            +extension RENDER \
            -logfile ./xdummy.log \
            -config /etc/X11/xorg.conf :1 &
          cd $GITHUB_WORKSPACE
          python3.7 -m venv "${venv_dir}"
          . "${venv_dir}"
          pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
          pip install -e .
          pip install -e .[train]
      - name: Test Learning
        run:
          cd $GITHUB_WORKSPACE
          . "${venv_dir}"
          make test-learning
