on:
  workflow_run:
    workflows: ["SMARTS CI Mac", "SMARTS CI Base Tests"]
    types: [completed]

jobs:
  # on-success:
  #   runs-on: ubuntu-18.04
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   steps:
  #     ...
  on-failure:
    container: huaweinoah/smarts:v0.4.18-minimal
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test pip packages
        run: |
          cd $GITHUB_WORKSPACE
          . ./utils/setup/test_pip_packages.sh