name: ULTRA CI Package Tests

on: [push, pull_request]

jobs:
    test-package:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    container: huaweinoah/smarts:v0.4.3-pre
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup X11
        run: |
          /usr/bin/Xorg \
            -noreset \
            +extension GLX \
            +extension RANDR \
            +extension RENDER \
            -logfile ./xdummy.log \
            -config /etc/X11/xorg.conf :1 &
      - name: Install ultra-rl
        run: |
          cd ultra/
          python3.7 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -e .
          scl scenario build-all ultra/scenarios/pool
          pytest -v tests/test_ultra_package.py




        
